MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-101-FPN-RETINANET"
    USE_P2: True    # add P2
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False # stride2 in 3*3 conv
    USE_DCN: True  # dcn = [False, True, True, True]
    # USE_DCN: False  # dcn = [False, False, False, False]
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  ROI_HEADS:
    DETECTIONS_PER_IMG: 5000
  USE_SYNCBN: True
  # add P2
  FCOS:
    CENTER_SAMPLE: True
    POS_RADIUS: 1.0
    FPN_STRIDES_ADDP2: [4, 8, 16, 32, 64, 128]
    LOC_LOSS_TYPE: "giou"
DATASETS:
  TRAIN: ("visdrone_train",)
  TEST: ("visdrone_val",)
INPUT:
  MIN_SIZE_TRAIN: (1500,)
  MAX_SIZE_TRAIN: 2500
  MIN_SIZE_TEST: 1500
  MAX_SIZE_TEST: 2500
  CROP_SIZE: 1024
  RANDOM_CROP_FIXED: True
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 8
  # IMS_PER_BATCH: 16
  # IMS_PER_BATCH: 1
  WARMUP_METHOD: "constant"
TEST:
  # DETECTIONS_PER_IMG: 1000
  DETECTIONS_PER_IMG: 5000
